### ISSUE TITLE
[FEAT] 공통 Login Page 구현

### ISSUE THREAD

**Issue by funfungun** [local-mark/frontend#11]
### 💼 작업 설명
(공통) 로그인 패이지를 구현합니다.
 
### ✅ To-do

- [x] todo 1 Figma 기반 UI 구현
- [x] todo 2 redux 기반 전역 상태 변수 관리
- [x] todo 3 기본 동작 이벤트핸들러 구현

### 💡기타 사항

- 서버 배포 후 동작 테스트 필요
- react hook form 전환 고려
