### ISSUE TITLE
[FEAT] 채팅 페이지 구현

### ISSUE THREAD

**Issue by funfungun** [local-mark/frontend#122]
### 💼 작업 설명

채팅 페이지를 구현합니다.
 
### ✅ To-do

- [ ] todo 1 채팅 페이지 레이아웃 구현
- [ ] todo 2 CSS Design & 이벤트 핸들러 구현
- [ ] todo 3 API 연동 & 에러 핸들링
