### ISSUE TITLE
[FEAT] (구매자) 제품 갤러리 페이지 구현

### ISSUE THREAD

**Issue by Jhcki222** [local-mark/frontend#14]
### 💼 작업 설명
제품 갤러리 페이지를 구현합니다.
 
### ✅ To-do

- [x] todo 1 : 사이드 바 컴포넌트 구현
- [x] todo 2 : 필터링 바 컴포넌트 구현
- [ ] todo 3 : 제품 상세 페이지 API 연결 테스트 요망

### 💡기타 사항

아직 디자인이 완전히 나오지 않아서 와이어 프레임 바탕으로 구현합니다.
