### ISSUE TITLE
[FEAT] 랜딩 페이지 구현

### ISSUE THREAD

**Issue by triangle-park** [local-mark/frontend#15]
### 💼 작업 설명

로그인 이전 상태의 랜딩 페이지 구현
 
### ✅ To-do

- [x] todo 1: 로컬 크리에이터 소개 생성
- [x] todo 2: 로컬크리에이터/소비자로 시작하기 버튼 생성
- [x] todo 3: 지금 둘러보기 버튼 생성

### 💡기타 사항

회원가입 페이지 완성되면 버튼과 페이지 연결하기
