### ISSUE TITLE
[Feat] (판매자)크리에이터 커뮤니티 페이지 구현

### ISSUE THREAD

**Issue by 2023148075** [local-mark/frontend#16]
### 💼 작업 설명

 (판매자)크리에이터 커뮤니티 페이지 구현
### ✅ To-do

- [ ] todo 1 잡담 / 질문 / 정보공유 로 탭 나누어서 게시판 제작
- [ ] todo 2 글쓰기 버튼 구현
- [ ] todo 3 글쓰기 탭 만들기

### 💡기타 사항

글을 작성하는 것에 대한 명확한 디자인과 설계가 나오지 않음 (에브리타임처럼 게시판에서 간단하게 작성할 수 있게 구현 / 네이버 블로그같이 새로운 탭으로 구현 등)
