### ISSUE TITLE
[FEAT] 공통 SignUp Page 구현

### ISSUE THREAD

**Issue by funfungun** [local-mark/frontend#21]
### 💼 작업 설명

 공통 회원가입 페이지를 구현합니다.

### ✅ To-do

- [x] todo 1 회원가입 Layout 설계
- [x] todo 2 회원가입 CSS 디자인
- [x] todo 3 이벤트 핸들러 구현

### 💡기타 사항

페이지 디자인의 변동사항이 있을 것 같아 일단 1차로 구현하겠습니다.
