### ISSUE TITLE
[Feat] MoreLocal 페이지 구현

### ISSUE THREAD

**Issue by smddkt** [local-mark/frontend#24]
### ✅ To-do

- [ ] todo 1  more local(공통) -로컬레터 페이지 구현
- [ ] todo 2 more local(공통) - 이벤트 페이지 구현
- [ ] todo 3 이벤트 상세 페이지 구현

### 💡기타 사항
와이어프레임 바탕으로 구현
