### ISSUE TITLE
[Feat] 내 브랜드 관리 페이지 구현

### ISSUE THREAD

**Issue by funfungun** [local-mark/frontend#43]
### 💼 작업 설명

(판매자) 내 브랜드 관리 페이지를 구현합니다. 

### ✅ To-do

- [ ] todo 1 Layout Design
- [ ] todo 2 CSS Design
- [ ] todo 3 Event handler
