### ISSUE TITLE
[FEAT] 브랜드 등록하기 페이지 구현

### ISSUE THREAD

**Issue by funfungun** [local-mark/frontend#46]
### 💼 작업 설명

브랜드 등록하기 페이지를 구현합니다.
 
### ✅ To-do

- [ ] todo 1 Layout Design
- [ ] todo 2 CSS Design
- [ ] todo 3 Event Handler
