### ISSUE TITLE
[Feat] 회원가입 페이지 2차 구현

### ISSUE THREAD

**Issue by funfungun** [local-mark/frontend#62]
### 💼 작업 설명

회원가입 페이지의 수정사항을 반영합니다.
 
### ✅ To-do

- [x] todo 1 유저 선택 토글 추가
- [x] todo 2 이메일 인증 버튼 추가
- [x] todo 3 아이디/이메일 입력 창 구분
